### ISSUE TITLE
Demo link is not valid

### ISSUE THREAD

**Issue by noyyyy** [liushuheng163/GlobeGrafter#1]
@liushuheng163 @Again1013 

The map generation is really cool. I love it. But the demo returns `welcome to nginx. How can I take a trial on this game
![image](https://github.com/liushuheng163/GlobeGrafter/assets/59097122/e2587425-c0e2-4516-9eae-52838d66b40b)

**Comment by FrostStarBook** [comment]
We added domain names and https, forgot to update, you try again https://rogue.cenozoic.xyz/
